#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), '..', 'config', 'environment')

def usage
  puts "Usage: ./import [scan name] [directory 1] [directory 2]"
end

if ARGV.size == 2
  scan = Scan.find_or_create_by_name(:name => ARGV.shift, :starts_at => Time.now, :output => '')

  scan.start!
  
  files = []
  
  ARGV.each do |arg|
    files << Dir.glob(File.join(arg, '*.nessus')) if File.directory?(arg)
  end
  
  files.flatten.each do |nessus_file|
    plugins_file = File.join(File.dirname(nessus_file), File.basename(nessus_file, ".nessus") + ".plugins")

    Nessus.process(scan, nessus_file, plugins_file)
  end
  
  scan.stop!
else
  usage
end